"""Join 테이블 추가

Revision ID: 0a9eec853df4
Revises: 394b27107c8a
Create Date: 2026-08-06 15:14:18.781549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9eec853df4'
down_revision = '394b27107c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('round_date', sa.Date(), nullable=False),
    sa.Column('tee_time', sa.String(length=10), nullable=True),
    sa.Column('course_info', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('recruit_count', sa.Integer(), nullable=True),
    sa.Column('filled_count', sa.Integer(), nullable=True),
    sa.Column('gender_condition', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('thumb_img', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['writer_id'], ['user.id'], name=op.f('fk_join_writer_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join')
    # ### end Alembic commands ###
