"""empty message

Revision ID: 394b27107c8a
Revises: 5cb2fd66f27f
Create Date: 2026-08-04 22:20:53.882425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394b27107c8a'
down_revision = '5cb2fd66f27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shaft_recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_weight', sa.Integer(), nullable=True),
    sa.Column('wood5_weight', sa.Integer(), nullable=True),
    sa.Column('utility4_weight', sa.Integer(), nullable=True),
    sa.Column('iron7_weight', sa.Integer(), nullable=True),
    sa.Column('driver_flex', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_shaft_recommend_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shaft_recommend'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=20), nullable=False))
        batch_op.alter_column('nickname',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('user_sex',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=1),
               existing_nullable=False)
        batch_op.alter_column('experience_years',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_user_user_id'), ['user_id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_user_user_id'), type_='unique')
        batch_op.alter_column('experience_years',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_sex',
               existing_type=sa.String(length=1),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('nickname',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    op.drop_table('shaft_recommend')
    # ### end Alembic commands ###
