"""add profile columns to user

Revision ID: 3aa12e169e7c
Revises: e06bfc07fed6
Create Date: 2026-08-07 23:43:12.388727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aa12e169e7c'
down_revision = 'e06bfc07fed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('golf_experience', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('golf_experience')
        batch_op.drop_column('home_address')
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
