"""empty message

Revision ID: 4152f795d196
Revises: 704d30e1d915
Create Date: 2026-08-06 16:39:18.190970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4152f795d196'
down_revision = '704d30e1d915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
