"""empty message

Revision ID: 5cb2fd66f27f
Revises: 5ff5cbec62f7
Create Date: 2026-08-03 17:57:44.804987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb2fd66f27f'
down_revision = '5ff5cbec62f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_sex', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('experience_years', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('experience_years')
        batch_op.drop_column('user_sex')

    # ### end Alembic commands ###
