"""initial migration

Revision ID: 6ff9e25b094c
Revises: 
Create Date: 2026-08-07 00:45:28.613888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff9e25b094c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    op.create_table('shop_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('main_img', sa.String(length=255), nullable=True),
    sa.Column('detail_img', sa.String(length=255), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('shipping', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_product'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('phonenumber', sa.String(length=20), nullable=False),
    sa.Column('user_sex', sa.String(length=1), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('nickname', name=op.f('uq_user_nickname')),
    sa.UniqueConstraint('phonenumber', name=op.f('uq_user_phonenumber')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_user_id'))
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_comment_post_id_post')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_table('join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('writer_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('round_date', sa.Date(), nullable=False),
    sa.Column('tee_time', sa.String(length=10), nullable=True),
    sa.Column('course_info', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('recruit_count', sa.Integer(), nullable=True),
    sa.Column('filled_count', sa.Integer(), nullable=True),
    sa.Column('gender_condition', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('thumb_img', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['writer_id'], ['user.id'], name=op.f('fk_join_writer_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join'))
    )
    op.create_table('product_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], name=op.f('fk_product_review_product_id_shop_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_product_review_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_review'))
    )
    op.create_table('shaft_recommend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('driver_weight', sa.Integer(), nullable=True),
    sa.Column('wood5_weight', sa.Integer(), nullable=True),
    sa.Column('utility4_weight', sa.Integer(), nullable=True),
    sa.Column('iron7_weight', sa.Integer(), nullable=True),
    sa.Column('driver_flex', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_shaft_recommend_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shaft_recommend'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shaft_recommend')
    op.drop_table('product_review')
    op.drop_table('join')
    op.drop_table('comment')
    op.drop_table('user')
    op.drop_table('shop_product')
    op.drop_table('post')
    # ### end Alembic commands ###
