"""JoinLike 테이블 추가

Revision ID: 72ff2635f812
Revises: 8ed8e7d7debb
Create Date: 2026-08-12 11:37:39.651949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ff2635f812'
down_revision = '8ed8e7d7debb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['join_id'], ['join.id'], name=op.f('fk_join_like_join_id_join')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_join_like_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_like'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_like')
    # ### end Alembic commands ###
