"""empty message

Revision ID: 771608dda117
Revises: 394b27107c8a
Create Date: 2026-08-06 16:33:09.042374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771608dda117'
down_revision = '394b27107c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('main_img', sa.String(length=255), nullable=True),
    sa.Column('detail_img', sa.String(length=255), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('shipping', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_product'))
    )
    op.create_table('product_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], name=op.f('fk_product_review_product_id_shop_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_product_review_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_review'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    op.drop_table('product_review')
    op.drop_table('shop_product')
    # ### end Alembic commands ###
