"""empty message

Revision ID: 8ed8e7d7debb
Revises: a7c3d9e21f48
Create Date: 2026-08-11 09:43:09.845981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed8e7d7debb'
down_revision = 'a7c3d9e21f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comment_parent_id_comment'), 'comment', ['parent_id'], ['id'])

    with op.batch_alter_table('join_apply', schema=None) as batch_op:
        batch_op.drop_column('golf_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_apply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('golf_experience', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_parent_id_comment'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
