"""cart_item 테이블 추가 (로그인 유저 장바구니 저장)

Revision ID: 8f2c4a9d5e1b
Revises: 3aa12e169e7c
Create Date: 2026-08-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2c4a9d5e1b'
down_revision = '3aa12e169e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], name=op.f('fk_cart_item_product_id_shop_product')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_cart_item_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_item'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_item')
    # ### end Alembic commands ###
