"""chat_message 테이블 추가

Revision ID: a7c3d9e21f48
Revises: f3b6a1c9d472
Create Date: 2026-08-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c3d9e21f48'
down_revision = 'f3b6a1c9d472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['join_id'], ['join.id'], name=op.f('fk_chat_message_join_id_join')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_chat_message_sender_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    # ### end Alembic commands ###
