"""page_visit 테이블 추가 (관리자 페이지 접속 시간대 통계용)

Revision ID: b21f7c4a9d33
Revises: 8f2c4a9d5e1b
Create Date: 2026-08-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21f7c4a9d33'
down_revision = 'da6d312855aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_page_visit_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_visit'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_visit')
    # ### end Alembic commands ###
