"""product_detail_block 테이블 추가 (샵 상세페이지 하단 텍스트/이미지 설명)

Revision ID: c47a1e2f9b6d
Revises: b21f7c4a9d33
Create Date: 2026-08-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47a1e2f9b6d'
down_revision = 'b21f7c4a9d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_detail_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=10), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['shop_product.id'], name=op.f('fk_product_detail_block_product_id_shop_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_detail_block'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_detail_block')
    # ### end Alembic commands ###
