"""sync alembic history

Revision ID: da6d312855aa
Revises: 8f2c4a9d5e1b
Create Date: 2026-08-09 12:40:22.056304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6d312855aa'
down_revision = '8f2c4a9d5e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_apply', schema=None) as batch_op:
        batch_op.drop_column('golf_experience')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_apply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('golf_experience', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
