"""Join, JoinApply 테이블 추가

Revision ID: e06bfc07fed6
Revises: 6ff9e25b094c
Create Date: 2026-08-07 11:56:23.516392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e06bfc07fed6'
down_revision = '6ff9e25b094c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('join_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=50), nullable=True),
    sa.Column('applicant_phone', sa.String(length=20), nullable=True),
    sa.Column('golf_experience', sa.String(length=20), nullable=True),
    sa.Column('handicap', sa.String(length=20), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['user.id'], name=op.f('fk_join_apply_applicant_id_user')),
    sa.ForeignKeyConstraint(['join_id'], ['join.id'], name=op.f('fk_join_apply_join_id_join')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_apply'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_apply')
    # ### end Alembic commands ###
