"""회원 정지/강제 탈퇴 컬럼 추가 (관리자 회원 관리 기능용)

Revision ID: f3b6a1c9d472
Revises: c47a1e2f9b6d
Create Date: 2026-08-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b6a1c9d472'
down_revision = 'c47a1e2f9b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_withdrawn', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_suspended', server_default=None)
        batch_op.alter_column('is_withdrawn', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_withdrawn')
        batch_op.drop_column('is_suspended')
    # ### end Alembic commands ###
